/**
 * Population-level NHANES statistics, not a per-individual prediction.
 * Backed by backend/src/data/nhanesPopulationContext.json, a static
 * artifact regenerated by benchmark/nhanes_stage/run.ts -- never hand-edited
 * and never recomputed at request time.
 */
export interface AgeBand {
  band: string
  minAge: number
  maxAge: number
  n: number
  distribution: Record<string, number>
}

export interface PopulationContextData {
  source: string
  generatedAt: string
  disclaimer: string
  ageBands: AgeBand[]
}

export function findAgeBand(age: number, data: PopulationContextData): AgeBand | null {
  return data.ageBands.find((b) => age >= b.minAge && age <= b.maxAge) ?? null
}
